CREATE DATABASE IF NOT EXISTS lab CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE lab;

CREATE TABLE IF NOT EXISTS roles (name VARCHAR(30) PRIMARY KEY, description TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(80) UNIQUE NOT NULL, email VARCHAR(160) UNIQUE NOT NULL, full_name VARCHAR(160) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(30) NOT NULL DEFAULT 'user', is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (role) REFERENCES roles(name));
CREATE TABLE IF NOT EXISTS device_groups (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) UNIQUE NOT NULL, description TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS locations (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) UNIQUE NOT NULL, building VARCHAR(120) NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS devices (id INT AUTO_INCREMENT PRIMARY KEY, asset_code VARCHAR(60) UNIQUE NOT NULL, name VARCHAR(160) NOT NULL, category VARCHAR(80) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'available', serial_number VARCHAR(120) NOT NULL DEFAULT '', group_id INT NULL, location_id INT NULL, FOREIGN KEY (group_id) REFERENCES device_groups(id), FOREIGN KEY (location_id) REFERENCES locations(id));
CREATE TABLE IF NOT EXISTS borrow_requests (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, device_id INT NOT NULL, purpose TEXT NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pending', requested_from DATETIME NULL, requested_to DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (device_id) REFERENCES devices(id));
CREATE TABLE IF NOT EXISTS usage_history (id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, device_id INT NOT NULL, borrow_request_id INT NULL, action VARCHAR(30) NOT NULL, occurred_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (device_id) REFERENCES devices(id), FOREIGN KEY (borrow_request_id) REFERENCES borrow_requests(id));
CREATE TABLE IF NOT EXISTS maintenance_schedules (id INT AUTO_INCREMENT PRIMARY KEY, device_id INT NOT NULL, interval_days INT NOT NULL DEFAULT 180, next_due_at DATETIME NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, notes TEXT NOT NULL DEFAULT '', FOREIGN KEY (device_id) REFERENCES devices(id));
CREATE TABLE IF NOT EXISTS maintenance_records (id INT AUTO_INCREMENT PRIMARY KEY, device_id INT NOT NULL, technician_id INT NULL, kind VARCHAR(40) NOT NULL DEFAULT 'inspection', notes TEXT NOT NULL DEFAULT '', status VARCHAR(30) NOT NULL DEFAULT 'open', scheduled_at DATETIME NULL, completed_at DATETIME NULL, FOREIGN KEY (device_id) REFERENCES devices(id), FOREIGN KEY (technician_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS documents (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(200) UNIQUE NOT NULL, description TEXT NOT NULL DEFAULT '', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS document_chunks (id INT AUTO_INCREMENT PRIMARY KEY, document_id INT NULL, document_name VARCHAR(200) NOT NULL, content TEXT NOT NULL, chunk_index INT NOT NULL DEFAULT 0, FOREIGN KEY (document_id) REFERENCES documents(id));

INSERT IGNORE INTO roles (name, description) VALUES ('admin','System administrator'),('manager','Lab manager'),('technician','Maintenance technician'),('user','Lab user');
INSERT IGNORE INTO users (id,username,email,full_name,password_hash,role,is_active) VALUES
(1,'admin','admin@lab.local','Lab Manager','$2b$12$LQv3c1yqBW1hW4D1f0VjUe8iQmDkq7h8n9w0x1y2z3a4b5c6d7e8f','admin',TRUE),
(2,'user','user@lab.local','Lab User','$2b$12$LQv3c1yqBW1hW4D1f0VjUe8iQmDkq7h8n9w0x1y2z3a4b5c6d7e8f','user',TRUE),
(3,'technician','tech@lab.local','Maintenance Technician','$2b$12$LQv3c1yqBW1hW4D1f0VjUe8iQmDkq7h8n9w0x1y2z3a4b5c6d7e8f','technician',TRUE);
INSERT IGNORE INTO device_groups (id,name,description) VALUES (1,'IoT','IoT devices'),(2,'Embedded','Embedded systems'),(3,'Electronics','Electronics'),(4,'Measurement','Measurement equipment'),(5,'Safety','Safety equipment');
INSERT IGNORE INTO locations (id,name,building) VALUES (1,'Lab A','Building A'),(2,'Lab B','Building A'),(3,'Storage','Building B');
INSERT IGNORE INTO devices (id,asset_code,name,category,status,serial_number,group_id,location_id) VALUES (1,'DEV-001','Oscilloscope 1','measurement','available','SN001',4,1),(2,'DEV-002','Oscilloscope 2','measurement','available','SN002',4,1),(3,'DEV-003','Multimeter 1','measurement','available','SN003',4,1),(4,'DEV-004','Arduino Kit 1','embedded','available','SN004',2,2),(5,'DEV-005','Arduino Kit 2','embedded','borrowed','SN005',2,2),(6,'DEV-006','Raspberry Pi 1','IoT','available','SN006',1,2),(7,'DEV-007','Raspberry Pi 2','IoT','maintenance','SN007',1,2),(8,'DEV-008','ESP32 Kit 1','IoT','available','SN008',1,2),(9,'DEV-009','Soldering Station 1','electronics','available','SN009',3,1),(10,'DEV-010','Soldering Station 2','electronics','available','SN010',3,1),(11,'DEV-011','Power Supply 1','electronics','available','SN011',3,1),(12,'DEV-012','Logic Analyzer','measurement','available','SN012',4,1),(13,'DEV-013','Safety Tester','safety','available','SN013',5,3),(14,'DEV-014','Sensor Kit 1','IoT','available','SN014',1,2),(15,'DEV-015','Sensor Kit 2','IoT','available','SN015',1,2);
INSERT IGNORE INTO borrow_requests (id,user_id,device_id,purpose,status) VALUES (1,2,1,'Signal analysis','pending'),(2,2,4,'Embedded lab','approved'),(3,2,6,'IoT prototype','pending'),(4,2,8,'Sensor test','returned'),(5,2,9,'Soldering','approved'),(6,2,10,'Circuit repair','pending'),(7,2,11,'Power test','returned'),(8,2,12,'Protocol analysis','pending'),(9,2,14,'IoT experiment','approved'),(10,2,15,'Data collection','pending');
INSERT IGNORE INTO documents (id,name,description) VALUES (1,'Lab SOP','Safety procedures'),(2,'Oscilloscope Manual','Operating manual');
INSERT IGNORE INTO document_chunks (id,document_id,document_name,content,chunk_index) VALUES (1,1,'Lab SOP','Thiết bị phải được kiểm tra an toàn trước khi sử dụng. Tuân thủ SOP và ngắt nguồn trước bảo trì.',0),(2,2,'Oscilloscope Manual','Kết nối probe đúng cực, chọn thang đo phù hợp và không vượt quá điện áp định mức.',0);